aplikasi_jadi: source/main.c source/admin.c source/user.c source/login.c source/utils.c
	gcc -Wall -o aplikasi_jadi source/main.c source/admin.c source/user.c source/login.c source/utils.c

clean:
	rm -f aplikasi_jadi